# Generated by Django 2.1.3 on 2018-11-30 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PERRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreperro', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ADOPTADO', 'ADOPTADO'), ('RESCATADO', 'RESCATADO'), ('DISPONIBLE', 'DISPONIBLE')], default='DISPONIBLE', max_length=80)),
                ('foto', models.CharField(max_length=340)),
                ('adoptador', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
